server:
    port: ${PORT:8081}

spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: import-api
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:movies-db}
        username: ${DB_USER:admin}
        password: ${DB_PASSWORD:123456}
        initialization-mode: always
        initialize: true
        continue-on-error: true
        platform: postgresql
        maxActive: 3
    jpa:
        hibernate:
            ddl-auto: create-drop
            format_sql: true
        show_sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
    rabbitmq:
        host: ${RABBIT_MQ_HOST:localhost}
        port: ${RABBIT_MQ_PORT:5672}
        username: ${RABBIT_MQ_USER:guest}
        password: ${RABBIT_MQ_PASSWORD:guest}

app:
    rabbit:
        exchange: movie.topic
        routingKey: movie.routingKey
        queue: movie.queue
